### ISSUE TITLE
some KeyErrors

### ISSUE THREAD

**Issue by josha33** [alberanid/imdbpy#218]
#### Issue description
I get this error when trying to get mpaa key :

Traceback (most recent call last):
  File "mdb.py", line 34, in <module>
    print(movie[0]['mpaa'])
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/imdb/utils.py", line 1499, in __getitem__
    rawData = self.data[key]
KeyError: 'mpaa'

#### Version of IMDbPY, Python and OS

- **Python:** 3.6
- **IMDbPY:** 6.7
- **OS:** centos 6

#### Steps to reproduce the issue
```
#!python

import imdb
ia = imdb.IMDb()
movie = ia.search_movie('fight club')
ia.update(movie[0])
print('movie[0]['mpaa'])

```
#### Additional details
output of  : print(movie[0].keys())

['title', 'kind', 'year', 'cast', 'genres', 'runtimes', 'countries', 'country codes', 'language codes', 'color info', 'aspect ratio', 'sound mix', 'certificates', 'original air date', 'rating', 'votes', 'cover url', 'plot outline', 'languages', 'directors', 'writers', 'producers', 'composers', 'cinematographers', 'editors', 'editorial department', 'casting directors', 'production designers', 'art directors', 'set decorators', 'costume designers', 'make up department', 'production managers', 'assistant directors', 'art department', 'sound department', 'special effects', 'visual effects', 'stunts', 'camera department', 'animation department', 'casting department', 'costume departmen', 'location management', 'music department', 'transportation department', 'miscellaneous', 'thanks', 'akas', 'writer', 'director', 'top 250 rank', 'production companies', 'distributors', 'special effects companies', 'other companies', 'plot', 'synopsis', 'canonical title', 'long imdb title', 'long imdb canonical title', 'smart canonical title', 'smart long imdb canonical title', 'full-size cover url']

output of : print(ia.get_movie_infoset())

['airing', 'akas', 'alternate versions', 'awards', 'connections', 'crazy credits', 'critic reviews', 'episodes', 'external reviews', 'external sites', 'faqs', 'full credits', 'goofs', 'keywords', 'locations', 'main', 'misc sites', 'news', 'official sites', 'parents guide', 'photo sites', 'plot', 'quotes', 'release dates', 'release info', 'reviews', 'sound clips', 'soundtrack', 'synopsis', 'taglines', 'technical', 'trivia', 'tv schedule', 'video clips', 'vote details']

I also can't get the release dates and some other keys from above.

**Comment by alberanid** [comment]
thanks for the report! MPAA extractor should be fixed in the master branch of this repository.

For other keys, please open another issue.

**Comment by rrgupta** [comment]
Hi,
I'm running imdb version 6.9dev20190905 and am still unable to get the 'mpaa' key to work. According to the [Docs](https://imdbpy.readthedocs.io/en/latest/usage/movie.html?highlight=mpaa#movies), 'mpaa' should still be a valid key in 'main'. Is that no longer true? Do I need to do as suggested in #110 and use the 'certifications' key and parse the result? Thanks.

**Comment by alberanid** [comment]
@rrgupta thanks for the notice, I've updated the documentation to confirm that 'mpaa' is no longer available amongst the main keys.

To collect it, you can do something like this:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import imdb
i = imdb.IMDb()
m = i.get_movie('0133093')
i.update(m, 'parents guide')
print(m['mpaa'])
```

**Comment by rrgupta** [comment]
Thanks @alberanid! 
For users who are interested, I found that for some movies (for whatever reason) the 'mpaa' field is missing from the 'parents guide' but can still be obtained from the 'certifications' (with more work needed to sort through them all). Here is an example for _Jaws (1975)_:
```
>>> import imdb
>>> i = imdb.IMDb()
>>> m = i.get_movie('0073195') # Jaws (1975)
>>> i.update(m, 'parents guide')
>>> print(m['mpaa'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ravigupta/miniconda3/lib/python3.7/site-packages/imdb/utils.py", line 1503, in __getitem__
    rawData = self.data[key]
KeyError: 'mpaa'
>>> c = m.get('certifications')
>>> print(c[54])
United States:PG
```
